# Archive Exploration 

a) Arthopod Prey species in Cali Dryland 

b) Synthesis of obervations 

c) 1945 - 2022

d) yes 

e) non-sensitive

In [5]:
import pandas as pd 
import numpy as np

In [18]:
# Metadata exploration 
meta = pd.read_csv("metadata.csv")
meta

# Data loading 
prey = pd.read_csv("occurrences.csv")
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56805,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.433250,-122.301699,2018-08-04T12:50:00Z,4.0,8.0,...,3299.612061,237.824051,40.644138,197.179916,91.536400,169.679627,0.978280,396.660706,evergreen_needleleaf,8294.923828
56806,Insecta,Hemiptera,Aphididae,Aphis,Aphis nerii,37.843269,-122.284744,2019-08-24T17:38:00Z,24.0,8.0,...,2821.564697,233.160873,62.358635,170.802246,107.255966,172.712341,0.816077,12.085342,NaN,2063.447266
56807,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,34.165164,-119.150376,2020-04-24T16:01:07Z,24.0,4.0,...,2505.230713,244.668579,64.761787,179.906799,127.800941,183.899994,1.052872,8.837754,urban,3182.021973
56808,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.453788,-122.109690,2020-07-08T11:51:00Z,8.0,7.0,...,3626.673340,250.658981,43.399197,207.259781,100.285355,188.197830,1.967808,1.993786,urban,3020.510742
56809,Insecta,Le,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# Look at your data 
prey.columns
pd.set_option("display.max.columns", None) #displayed ALL columns in dataframe! 
prey
pd.set_option("display.max_row", 4) #only displays 5 rows 
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020.0,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1.0,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021.0,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2.0,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56808,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.453788,-122.109690,2020-07-08T11:51:00Z,8.0,7.0,2020.0,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,56809.0,146.858429,190.391663,98.453545,388.265533,80.022423,1.000000,86.339668,205.585587,5.000000,8.083245,205.585587,111.148552,53.272911,3626.673340,250.658981,43.399197,207.259781,100.285355,188.197830,1.967808,1.993786,urban,3020.510742
56809,Insecta,Le,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
# preliminary exploration 

prey.head() # First 5 rows in df 
prey.tail() # Last 4 rows in df 
prey.info() # Looks at details of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56810 entries, 0 to 56809
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   class                          56810 non-null  object
 1   order                          56710 non-null  object
 2   family                         56809 non-null  object
 3   genus                          56809 non-null  object
 4   species                        56809 non-null  object
 5   lat                            56809 non-null  float64
 6   long                           56809 non-null  float64
 7   eventDate                      56809 non-null  object
 8   day                            56767 non-null  float64
 9   month                          56806 non-null  float64
 10  year                           56809 non-null  float64
 11  institutionCode                56215 non-null  object
 12  coordinateUncertaintyInMeters  41904 non-null  float64
 13  basisOfRecord                  56809 non-null  object
 14  individualCount                1752 non-null   float64
 15  datasetKey                     56809 non-null  object
 16  ID                             56809 non-null  float64
 17  bio1                           55925 non-null  float64
 18  bio10                          55925 non-null  float64
 19  bio11                          55925 non-null  float64
 20  bio12                          55925 non-null  float64
 21  bio13                          55925 non-null  float64
 22  bio14                          55925 non-null  float64
 23  bio15                          55925 non-null  float64
 24  bio16                          55925 non-null  float64
 25  bio17                          55925 non-null  float64
 26  bio18                          55925 non-null  float64
 27  bio19                          55925 non-null  float64
 28  bio2                           55925 non-null  float64
 29  bio3                           55925 non-null  float64
 30  bio4                           55925 non-null  float64
 31  bio5                           55925 non-null  float64
 32  bio6                           55925 non-null  float64
 33  bio7                           55925 non-null  float64
 34  bio8                           55925 non-null  float64
 35  bio9                           55925 non-null  float64
 36  dist                           55856 non-null  float64
 37  dem90_hf                       54970 non-null  float64
 38  lc_class                       54543 non-null  object
 39  ndvi                           55921 non-null  float64
dtypes: float64(30), object(10)
memory usage: 17.3+ MB

In [40]:
prey.nunique() # Gives number of uqiue values in each column

class           4
order          19
            ...
lc_class       12
ndvi        20025
Length: 40, dtype: int64

In [45]:
prey.shape # Returns number of rows, number of columns in df 
prey.columns # Returns column names 
prey.dtypes # Returns the columns data class

class        object
order        object
             ...
lc_class     object
ndvi        float64
Length: 40, dtype: object